### ISSUE TITLE
Qestion 

### ISSUE THREAD

**Issue by LamnouarMohamed** [SherryJYC/paper-MTMC#1]
Hi,

Thank you so much for sharing this repository

This Solution for online or offline DyGLIP: A Dynamic Graph Model with Link Prediction for Accurate Multi-Camera Multiple Object Tracking, Quach et al. [[paper]](https://openaccess.thecvf.com/content/CVPR2021/papers/Quach_DyGLIP_A_Dynamic_Graph_Model_With_Link_Prediction_for_Accurate_CVPR_2021_paper.pdf)

thank you again

**Comment by SherryJYC** [comment]
HI, the proposed method of this paper is online.

**Comment by LamnouarMohamed** [comment]
Thank you so much for reply.
